<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SchoolProject.Data\SchoolProject.Data.csproj" />
    <ProjectReference Include="..\SchoolProject.Infrasturcture\SchoolProject.Infrasturcture.csproj" />
    <ProjectReference Include="..\SchoolProject.Service\SchoolProject.Service.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Feature\Students\Commands\Handlers\" />
    <Folder Include="Feature\Students\Commands\Models\" />
    <Folder Include="Feature\Students\Commands\Validators\" />
    <Folder Include="Feature\Students\Qureies\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="14.2.0" />
  </ItemGroup>

</Project>
